export * from './MovieInfo'
export * from './AsideInfo'
export * from './RecommendationSwiper'
export * from './RecommendationMovieSlide'
export * from './GalleryMovie'
export * from './Reviews'
export * from './ReviewMovieSlide'